version: "2"
services:
  go-server:
    image: gocd/gocd-server:17.1.0
    container_name: gocd-server
    volumes:
        - ./gocd-data/conf/cruise-config.xml:/etc/go/cruise-config.xml
        - ./gocd-data/yaml-config-plugin-0.4.0.jar:/var/lib/go-server/plugins/external/yaml-config-plugin-0.4.0.jar
        - ./gocd-data/server:/var/lib/go-server
    ports:
        - 8153:8153
    environment:
        - SERVICE_NAME=gocd-server
        - AGENT_KEY=123456789abcdef
  go-agent:
    image: stakater/gocd-agent:17.1.0
    container_name: gocd-agent
    depends_on:
        - "go-server"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /opt/bin/docker-compose:/opt/bin/docker-compose
# - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/libltdl.so.7
    environment:
        - SERVICE_NAME=gocd-agent
        - AGENT_KEY=123456789abcdef
    links:
        - go-server
