logstash:
 image: stakater/logstash:5.2.1
 container_name: logstash
 ports:
   - 5044:5044
 links:
   - elasticsearch:elasticsearch
 volumes:
   - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
 labels:
   - SERVICE_NAME=logstash

elasticsearch:
 image: stakater/elasticsearch:5.2.1
 container_name: elasticsearch
 labels:
   - SERVICE_NAME=elasticsearch
 ports:
   - 9200:9200
   - 9300:9300

kibana:
 image: stakater/kibana:5.2.1
 container_name: kibana
 ports:
   - 5601:5601
 environment:
   - ELASTICSEARCH_URL=http://elasticsearch:9200
 links:
   - elasticsearch:elasticsearch
 labels:
   - SERVICE_NAME=kibana

filebeat:
 image: stakater/filebeat:5.2.1
 container_name: filebeat
 links:
   - logstash:logstash
 environment:
   - LOGSTASH_HOST=logstash
   - LOGSTASH_PORT=5044
 volumes:
   - ./logs:/var/log/stakater/sample
 labels:
   - SERVICE_NAME=filebeat